# Generated by Django 4.2.2 on 2023-07-17 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_arts_events_teammember_transaction_user_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='art',
        ),
    ]
